//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Proyecto.ws {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clCita", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class clCita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CedulaPacienteField;
        
        private string DiaCitaField;
        
        private decimal EspecialidadField;
        
        private string EstadoField;
        
        private System.DateTime FechaCitaField;
        
        private decimal HoraCitaField;
        
        private decimal IDCitaField;
        
        private System.Nullable<decimal> IDFacturaField;
        
        private decimal MedicoField;
        
        private string ObservacionesField;
        
        private decimal SedeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaPaciente {
            get {
                return this.CedulaPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaPacienteField, value) != true)) {
                    this.CedulaPacienteField = value;
                    this.RaisePropertyChanged("CedulaPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaCita {
            get {
                return this.DiaCitaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaCitaField, value) != true)) {
                    this.DiaCitaField = value;
                    this.RaisePropertyChanged("DiaCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((this.EspecialidadField.Equals(value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCita {
            get {
                return this.FechaCitaField;
            }
            set {
                if ((this.FechaCitaField.Equals(value) != true)) {
                    this.FechaCitaField = value;
                    this.RaisePropertyChanged("FechaCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HoraCita {
            get {
                return this.HoraCitaField;
            }
            set {
                if ((this.HoraCitaField.Equals(value) != true)) {
                    this.HoraCitaField = value;
                    this.RaisePropertyChanged("HoraCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDCita {
            get {
                return this.IDCitaField;
            }
            set {
                if ((this.IDCitaField.Equals(value) != true)) {
                    this.IDCitaField = value;
                    this.RaisePropertyChanged("IDCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IDFactura {
            get {
                return this.IDFacturaField;
            }
            set {
                if ((this.IDFacturaField.Equals(value) != true)) {
                    this.IDFacturaField = value;
                    this.RaisePropertyChanged("IDFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Medico {
            get {
                return this.MedicoField;
            }
            set {
                if ((this.MedicoField.Equals(value) != true)) {
                    this.MedicoField = value;
                    this.RaisePropertyChanged("Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((this.SedeField.Equals(value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clPacienteCNA", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class clPacienteCNA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApellidoField;
        
        private string CedulaField;
        
        private string NombreField;
        
        private string forUIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string forUI {
            get {
                return this.forUIField;
            }
            set {
                if ((object.ReferenceEquals(this.forUIField, value) != true)) {
                    this.forUIField = value;
                    this.RaisePropertyChanged("forUI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clEmpleadoANNII", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class clEmpleadoANNII : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApellidosField;
        
        private string EspecialidadField;
        
        private decimal IDEmpleadoField;
        
        private decimal IDEspecialidadField;
        
        private string NombreField;
        
        private string forUIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDEmpleado {
            get {
                return this.IDEmpleadoField;
            }
            set {
                if ((this.IDEmpleadoField.Equals(value) != true)) {
                    this.IDEmpleadoField = value;
                    this.RaisePropertyChanged("IDEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDEspecialidad {
            get {
                return this.IDEspecialidadField;
            }
            set {
                if ((this.IDEspecialidadField.Equals(value) != true)) {
                    this.IDEspecialidadField = value;
                    this.RaisePropertyChanged("IDEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string forUI {
            get {
                return this.forUIField;
            }
            set {
                if ((object.ReferenceEquals(this.forUIField, value) != true)) {
                    this.forUIField = value;
                    this.RaisePropertyChanged("forUI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clSede", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class clSede : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal IDSedeField;
        
        private string RazonSocialField;
        
        private string forUIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDSede {
            get {
                return this.IDSedeField;
            }
            set {
                if ((this.IDSedeField.Equals(value) != true)) {
                    this.IDSedeField = value;
                    this.RaisePropertyChanged("IDSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string forUI {
            get {
                return this.forUIField;
            }
            set {
                if ((object.ReferenceEquals(this.forUIField, value) != true)) {
                    this.forUIField = value;
                    this.RaisePropertyChanged("forUI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clHorario", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class clHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DiaField;
        
        private decimal HoraField;
        
        private string forUIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dia {
            get {
                return this.DiaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaField, value) != true)) {
                    this.DiaField = value;
                    this.RaisePropertyChanged("Dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((this.HoraField.Equals(value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string forUI {
            get {
                return this.forUIField;
            }
            set {
                if ((object.ReferenceEquals(this.forUIField, value) != true)) {
                    this.forUIField = value;
                    this.RaisePropertyChanged("forUI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ws.wsCentroMedico")]
    public interface wsCentroMedico {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/wsCentroMedico/getCitas", ReplyAction="http://tempuri.org/wsCentroMedico/getCitasResponse")]
        System.IAsyncResult BegingetCitas(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> EndgetCitas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/wsCentroMedico/getPacientes", ReplyAction="http://tempuri.org/wsCentroMedico/getPacientesResponse")]
        System.IAsyncResult BegingetPacientes(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> EndgetPacientes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/wsCentroMedico/getMedicos", ReplyAction="http://tempuri.org/wsCentroMedico/getMedicosResponse")]
        System.IAsyncResult BegingetMedicos(int sede, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> EndgetMedicos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/wsCentroMedico/getSedes", ReplyAction="http://tempuri.org/wsCentroMedico/getSedesResponse")]
        System.IAsyncResult BegingetSedes(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> EndgetSedes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/wsCentroMedico/getHorarios", ReplyAction="http://tempuri.org/wsCentroMedico/getHorariosResponse")]
        System.IAsyncResult BegingetHorarios(decimal Medico, decimal Sede, string Dia, System.DateTime Fecha, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> EndgetHorarios(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCentroMedicoChannel : Proyecto.ws.wsCentroMedico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCitasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCitasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPacientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getPacientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMedicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMedicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSedesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSedesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getHorariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getHorariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCentroMedicoClient : System.ServiceModel.ClientBase<Proyecto.ws.wsCentroMedico>, Proyecto.ws.wsCentroMedico {
        
        private BeginOperationDelegate onBegingetCitasDelegate;
        
        private EndOperationDelegate onEndgetCitasDelegate;
        
        private System.Threading.SendOrPostCallback ongetCitasCompletedDelegate;
        
        private BeginOperationDelegate onBegingetPacientesDelegate;
        
        private EndOperationDelegate onEndgetPacientesDelegate;
        
        private System.Threading.SendOrPostCallback ongetPacientesCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMedicosDelegate;
        
        private EndOperationDelegate onEndgetMedicosDelegate;
        
        private System.Threading.SendOrPostCallback ongetMedicosCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSedesDelegate;
        
        private EndOperationDelegate onEndgetSedesDelegate;
        
        private System.Threading.SendOrPostCallback ongetSedesCompletedDelegate;
        
        private BeginOperationDelegate onBegingetHorariosDelegate;
        
        private EndOperationDelegate onEndgetHorariosDelegate;
        
        private System.Threading.SendOrPostCallback ongetHorariosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public wsCentroMedicoClient() {
        }
        
        public wsCentroMedicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCentroMedicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCentroMedicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCentroMedicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getCitasCompletedEventArgs> getCitasCompleted;
        
        public event System.EventHandler<getPacientesCompletedEventArgs> getPacientesCompleted;
        
        public event System.EventHandler<getMedicosCompletedEventArgs> getMedicosCompleted;
        
        public event System.EventHandler<getSedesCompletedEventArgs> getSedesCompleted;
        
        public event System.EventHandler<getHorariosCompletedEventArgs> getHorariosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proyecto.ws.wsCentroMedico.BegingetCitas(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCitas(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> Proyecto.ws.wsCentroMedico.EndgetCitas(System.IAsyncResult result) {
            return base.Channel.EndgetCitas(result);
        }
        
        private System.IAsyncResult OnBegingetCitas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Proyecto.ws.wsCentroMedico)(this)).BegingetCitas(callback, asyncState);
        }
        
        private object[] OnEndgetCitas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> retVal = ((Proyecto.ws.wsCentroMedico)(this)).EndgetCitas(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCitasCompleted(object state) {
            if ((this.getCitasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCitasCompleted(this, new getCitasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCitasAsync() {
            this.getCitasAsync(null);
        }
        
        public void getCitasAsync(object userState) {
            if ((this.onBegingetCitasDelegate == null)) {
                this.onBegingetCitasDelegate = new BeginOperationDelegate(this.OnBegingetCitas);
            }
            if ((this.onEndgetCitasDelegate == null)) {
                this.onEndgetCitasDelegate = new EndOperationDelegate(this.OnEndgetCitas);
            }
            if ((this.ongetCitasCompletedDelegate == null)) {
                this.ongetCitasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCitasCompleted);
            }
            base.InvokeAsync(this.onBegingetCitasDelegate, null, this.onEndgetCitasDelegate, this.ongetCitasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proyecto.ws.wsCentroMedico.BegingetPacientes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetPacientes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> Proyecto.ws.wsCentroMedico.EndgetPacientes(System.IAsyncResult result) {
            return base.Channel.EndgetPacientes(result);
        }
        
        private System.IAsyncResult OnBegingetPacientes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Proyecto.ws.wsCentroMedico)(this)).BegingetPacientes(callback, asyncState);
        }
        
        private object[] OnEndgetPacientes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> retVal = ((Proyecto.ws.wsCentroMedico)(this)).EndgetPacientes(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetPacientesCompleted(object state) {
            if ((this.getPacientesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getPacientesCompleted(this, new getPacientesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getPacientesAsync() {
            this.getPacientesAsync(null);
        }
        
        public void getPacientesAsync(object userState) {
            if ((this.onBegingetPacientesDelegate == null)) {
                this.onBegingetPacientesDelegate = new BeginOperationDelegate(this.OnBegingetPacientes);
            }
            if ((this.onEndgetPacientesDelegate == null)) {
                this.onEndgetPacientesDelegate = new EndOperationDelegate(this.OnEndgetPacientes);
            }
            if ((this.ongetPacientesCompletedDelegate == null)) {
                this.ongetPacientesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetPacientesCompleted);
            }
            base.InvokeAsync(this.onBegingetPacientesDelegate, null, this.onEndgetPacientesDelegate, this.ongetPacientesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proyecto.ws.wsCentroMedico.BegingetMedicos(int sede, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMedicos(sede, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> Proyecto.ws.wsCentroMedico.EndgetMedicos(System.IAsyncResult result) {
            return base.Channel.EndgetMedicos(result);
        }
        
        private System.IAsyncResult OnBegingetMedicos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int sede = ((int)(inValues[0]));
            return ((Proyecto.ws.wsCentroMedico)(this)).BegingetMedicos(sede, callback, asyncState);
        }
        
        private object[] OnEndgetMedicos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> retVal = ((Proyecto.ws.wsCentroMedico)(this)).EndgetMedicos(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMedicosCompleted(object state) {
            if ((this.getMedicosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMedicosCompleted(this, new getMedicosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMedicosAsync(int sede) {
            this.getMedicosAsync(sede, null);
        }
        
        public void getMedicosAsync(int sede, object userState) {
            if ((this.onBegingetMedicosDelegate == null)) {
                this.onBegingetMedicosDelegate = new BeginOperationDelegate(this.OnBegingetMedicos);
            }
            if ((this.onEndgetMedicosDelegate == null)) {
                this.onEndgetMedicosDelegate = new EndOperationDelegate(this.OnEndgetMedicos);
            }
            if ((this.ongetMedicosCompletedDelegate == null)) {
                this.ongetMedicosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMedicosCompleted);
            }
            base.InvokeAsync(this.onBegingetMedicosDelegate, new object[] {
                        sede}, this.onEndgetMedicosDelegate, this.ongetMedicosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proyecto.ws.wsCentroMedico.BegingetSedes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSedes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> Proyecto.ws.wsCentroMedico.EndgetSedes(System.IAsyncResult result) {
            return base.Channel.EndgetSedes(result);
        }
        
        private System.IAsyncResult OnBegingetSedes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Proyecto.ws.wsCentroMedico)(this)).BegingetSedes(callback, asyncState);
        }
        
        private object[] OnEndgetSedes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> retVal = ((Proyecto.ws.wsCentroMedico)(this)).EndgetSedes(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSedesCompleted(object state) {
            if ((this.getSedesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSedesCompleted(this, new getSedesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSedesAsync() {
            this.getSedesAsync(null);
        }
        
        public void getSedesAsync(object userState) {
            if ((this.onBegingetSedesDelegate == null)) {
                this.onBegingetSedesDelegate = new BeginOperationDelegate(this.OnBegingetSedes);
            }
            if ((this.onEndgetSedesDelegate == null)) {
                this.onEndgetSedesDelegate = new EndOperationDelegate(this.OnEndgetSedes);
            }
            if ((this.ongetSedesCompletedDelegate == null)) {
                this.ongetSedesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSedesCompleted);
            }
            base.InvokeAsync(this.onBegingetSedesDelegate, null, this.onEndgetSedesDelegate, this.ongetSedesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Proyecto.ws.wsCentroMedico.BegingetHorarios(decimal Medico, decimal Sede, string Dia, System.DateTime Fecha, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetHorarios(Medico, Sede, Dia, Fecha, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> Proyecto.ws.wsCentroMedico.EndgetHorarios(System.IAsyncResult result) {
            return base.Channel.EndgetHorarios(result);
        }
        
        private System.IAsyncResult OnBegingetHorarios(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal Medico = ((decimal)(inValues[0]));
            decimal Sede = ((decimal)(inValues[1]));
            string Dia = ((string)(inValues[2]));
            System.DateTime Fecha = ((System.DateTime)(inValues[3]));
            return ((Proyecto.ws.wsCentroMedico)(this)).BegingetHorarios(Medico, Sede, Dia, Fecha, callback, asyncState);
        }
        
        private object[] OnEndgetHorarios(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> retVal = ((Proyecto.ws.wsCentroMedico)(this)).EndgetHorarios(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetHorariosCompleted(object state) {
            if ((this.getHorariosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getHorariosCompleted(this, new getHorariosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getHorariosAsync(decimal Medico, decimal Sede, string Dia, System.DateTime Fecha) {
            this.getHorariosAsync(Medico, Sede, Dia, Fecha, null);
        }
        
        public void getHorariosAsync(decimal Medico, decimal Sede, string Dia, System.DateTime Fecha, object userState) {
            if ((this.onBegingetHorariosDelegate == null)) {
                this.onBegingetHorariosDelegate = new BeginOperationDelegate(this.OnBegingetHorarios);
            }
            if ((this.onEndgetHorariosDelegate == null)) {
                this.onEndgetHorariosDelegate = new EndOperationDelegate(this.OnEndgetHorarios);
            }
            if ((this.ongetHorariosCompletedDelegate == null)) {
                this.ongetHorariosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetHorariosCompleted);
            }
            base.InvokeAsync(this.onBegingetHorariosDelegate, new object[] {
                        Medico,
                        Sede,
                        Dia,
                        Fecha}, this.onEndgetHorariosDelegate, this.ongetHorariosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Proyecto.ws.wsCentroMedico CreateChannel() {
            return new wsCentroMedicoClientChannel(this);
        }
        
        private class wsCentroMedicoClientChannel : ChannelBase<Proyecto.ws.wsCentroMedico>, Proyecto.ws.wsCentroMedico {
            
            public wsCentroMedicoClientChannel(System.ServiceModel.ClientBase<Proyecto.ws.wsCentroMedico> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetCitas(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getCitas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> EndgetCitas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita> _result = ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clCita>)(base.EndInvoke("getCitas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetPacientes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getPacientes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> EndgetPacientes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA> _result = ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clPacienteCNA>)(base.EndInvoke("getPacientes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetMedicos(int sede, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sede;
                System.IAsyncResult _result = base.BeginInvoke("getMedicos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> EndgetMedicos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII> _result = ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clEmpleadoANNII>)(base.EndInvoke("getMedicos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSedes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getSedes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> EndgetSedes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede> _result = ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clSede>)(base.EndInvoke("getSedes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetHorarios(decimal Medico, decimal Sede, string Dia, System.DateTime Fecha, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = Medico;
                _args[1] = Sede;
                _args[2] = Dia;
                _args[3] = Fecha;
                System.IAsyncResult _result = base.BeginInvoke("getHorarios", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> EndgetHorarios(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario> _result = ((System.Collections.ObjectModel.ObservableCollection<Proyecto.ws.clHorario>)(base.EndInvoke("getHorarios", _args, result)));
                return _result;
            }
        }
    }
}
